### ISSUE TITLE
"export" command fails asking for base64 encoding

### ISSUE THREAD

**Issue by samurang87** [igordertigor/jiraprinter#4]
Top of stacktrace:

```
Traceback (most recent call last):
  File "/Users/cmezzavilla/Envs/jiraprinter/bin/jira.py", line 199, in <module>
    credentials: 'should contain username:password in base64 encoding
```

**Comment by igordertigor** [comment]
Can you send a bit more of the stacktrace? Are you using python2? This only works with python3.

**Comment by samurang87** [comment]
I'm using python 3.7.3 :)

The stacktrace is huge. This is the part that doesn't look like html:

`Traceback (most recent call last):
  File "/Users/cmezzavilla/Envs/jiraprinter/bin/jira.py", line 199, in <module>
    credentials: 'should contain username:password in base64 encoding'
  File "/Users/cmezzavilla/Envs/jiraprinter/lib/python3.7/site-packages/begin/main.py", line 115, in _start
    prog.start()
  File "/Users/cmezzavilla/Envs/jiraprinter/lib/python3.7/site-packages/begin/main.py", line 54, in start
    collector=self._collector)
  File "/Users/cmezzavilla/Envs/jiraprinter/lib/python3.7/site-packages/begin/cmdline.py", line 258, in apply_options
    return_value = call_function(subfunc, signature(subfunc), opts)
  File "/Users/cmezzavilla/Envs/jiraprinter/lib/python3.7/site-packages/begin/cmdline.py", line 236, in call_function
    return func(*pargs, **kwargs)
  File "/Users/cmezzavilla/Envs/jiraprinter/bin/jira.py", line 192, in export
    jira_printer.process(ticket_ids)
  File "/Users/cmezzavilla/Envs/jiraprinter/bin/jira.py", line 50, in process
    tickets = [self.get_processed_issue(ticket_id) for ticket_id in ticket_ids]
  File "/Users/cmezzavilla/Envs/jiraprinter/bin/jira.py", line 50, in <listcomp>
    tickets = [self.get_processed_issue(ticket_id) for ticket_id in ticket_ids]
  File "/Users/cmezzavilla/Envs/jiraprinter/bin/jira.py", line 55, in get_processed_issue
    ticket = self.get_raw_issue(ticket_id)
  File "/Users/cmezzavilla/Envs/jiraprinter/bin/jira.py", line 68, in get_raw_issue
    raise requests.exceptions.HTTPError('{} (Error code={})'.format(response.content, response.status_code))
requests.exceptions.HTTPError: b'\n\n\n\n\n\n\n\n\n\n<html>\n\n<head>\n    <title>Unauthorized (401)</title>\n  ... `

**Comment by igordertigor** [comment]
It looks as if your credentials are incorrect. You're getting a 401 error when you try to receive the ticket. I could see two reasons for that
1. You are not using the correct username and password (or you didn't properly encode them as b64),
2. The jira API changed and doesn't allow basic auth anymore.
Can you access the url by hand? You can do that by (for example using `curl` on the url `<your-jira-api>/issue/<your-issue-number>`. I don't know the url for the jira api, which is why I left that as a placeholder and (to try it out), you would need at least the id of one ticket. You also need to set headers, so the total command would be
```
curl -H "Content-Type: application/json" -H "Authorization: Basic <B64CREDENTIALS>" <URL>
```
If you get a 401 error with that, it's simply an authorizaton problem.
